// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.messages;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;

/**
 *
 * A Building plus a location within the starfield map.
 */
public final class BuildingPosition extends Message {

  public static final Long DEFAULT_SECTOR_X = 0L;
  public static final Long DEFAULT_SECTOR_Y = 0L;
  public static final Integer DEFAULT_OFFSET_X = 0;
  public static final Integer DEFAULT_OFFSET_Y = 0;

  @ProtoField(tag = 1)
  public final Building building;

  @ProtoField(tag = 2, type = INT64)
  public final Long sector_x;

  @ProtoField(tag = 3, type = INT64)
  public final Long sector_y;

  @ProtoField(tag = 4, type = INT32)
  public final Integer offset_x;

  @ProtoField(tag = 5, type = INT32)
  public final Integer offset_y;

  public BuildingPosition(Building building, Long sector_x, Long sector_y, Integer offset_x, Integer offset_y) {
    this.building = building;
    this.sector_x = sector_x;
    this.sector_y = sector_y;
    this.offset_x = offset_x;
    this.offset_y = offset_y;
  }

  private BuildingPosition(Builder builder) {
    this(builder.building, builder.sector_x, builder.sector_y, builder.offset_x, builder.offset_y);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BuildingPosition)) return false;
    BuildingPosition o = (BuildingPosition) other;
    return equals(building, o.building)
        && equals(sector_x, o.sector_x)
        && equals(sector_y, o.sector_y)
        && equals(offset_x, o.offset_x)
        && equals(offset_y, o.offset_y);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = building != null ? building.hashCode() : 0;
      result = result * 37 + (sector_x != null ? sector_x.hashCode() : 0);
      result = result * 37 + (sector_y != null ? sector_y.hashCode() : 0);
      result = result * 37 + (offset_x != null ? offset_x.hashCode() : 0);
      result = result * 37 + (offset_y != null ? offset_y.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BuildingPosition> {

    public Building building;
    public Long sector_x;
    public Long sector_y;
    public Integer offset_x;
    public Integer offset_y;

    public Builder() {
    }

    public Builder(BuildingPosition message) {
      super(message);
      if (message == null) return;
      this.building = message.building;
      this.sector_x = message.sector_x;
      this.sector_y = message.sector_y;
      this.offset_x = message.offset_x;
      this.offset_y = message.offset_y;
    }

    public Builder building(Building building) {
      this.building = building;
      return this;
    }

    public Builder sector_x(Long sector_x) {
      this.sector_x = sector_x;
      return this;
    }

    public Builder sector_y(Long sector_y) {
      this.sector_y = sector_y;
      return this;
    }

    public Builder offset_x(Integer offset_x) {
      this.offset_x = offset_x;
      return this;
    }

    public Builder offset_y(Integer offset_y) {
      this.offset_y = offset_y;
      return this;
    }

    @Override
    public BuildingPosition build() {
      return new BuildingPosition(this);
    }
  }
}
